# Generated by Django 4.0.5 on 2022-06-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField()),
                ('parentezco', models.CharField(max_length=15)),
                ('fecha_cumpleanios', models.DateField()),
            ],
        ),
    ]
